CREATE TABLE APP.HOSTS
(
  HOST_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  HOST_NAME VARCHAR(50) NOT NULL,
  IP_ADDR VARCHAR(255),
  DESCRIPTION VARCHAR(2048),
  CREATE_DATE TIMESTAMP NOT NULL,
  MODIFY_DATE TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX "hosts_host_id_uindex" ON APP.hosts (host_id);
CREATE UNIQUE INDEX "hosts_host_name_uindex" ON APP.hosts (host_name);

CREATE TABLE APP.MONITOR_TARGETS
(
  MONITOR_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
  HOST_ID INTEGER NOT NULL REFERENCES HOSTS(HOST_ID),
  MONITOR_TYPE VARCHAR(45) NOT NULL,
  MONITOR_PORT INT
);

CREATE UNIQUE INDEX "monitor_targets_id_uindex" ON APP.MONITOR_TARGETS (MONITOR_ID);

CREATE TABLE APP.MONITOR_STATUS
(
  MONITOR_ID INTEGER NOT NULL,
  MONITOR_TIME TIMESTAMP NOT NULL,
  MONITOR_STATUS VARCHAR(45) NOT NULL,
  CONSTRAINT MONITOR_FK FOREIGN KEY (MONITOR_ID) REFERENCES MONITOR_TARGETS(MONITOR_ID)
);
